export default {
  ru: {
    "landing-title": "signal - онлайн MIDI-секвенсор",
    "app-intro": "создавайте музыку в своем браузере",
    "app-desc": "Готовое к использованию бесплатное программное обеспечение для редактирования MIDI",
    launch: "Запуск",
    platform:
        "Поддерживаемые браузеры: Google Chrome / Firefox / Safari",
    features: "Функции",
    "feature-midi-file": "Полнофункциональный MIDI-редактор",
    "feature-midi-file-description":
        "Проявите творческий подход с помощью редактора пианино, который поддерживает несколько дорожек. Конечно, вы можете создавать богатые выражения, используя динамическую чувствительность, изменение высоты тона, экспрессию и модуляцию.",
    "feature-gm-module": "Оснащен тон-генератором, совместимым с GM.",
    "feature-gm-module-description":
        "Специальный звуковой модуль, созданный с помощью WebAudio API и AudioWorklet, позволяет воспроизводить большое количество нот MIDI в браузере.",
    "piano-roll": "Пианорол",
    tempo: "Темп",
    "tempo-track": "Дорожка с темпом",
    "feature-time-signature": "Поддерживает тактовый размер и изменения темпа, кроме 4/4",
    "feature-time-signature-description":
        "Вы можете свободно менять темп и тактовый размер в середине песни с помощью графического редактора.",
    "feature-pwa": "PWA",
    "feature-pwa-description":
        "Ваша адресная строка мешает? Его можно установить как приложение.",
    "feature-export-wav": "Экспорт в WAV-файл",
    "feature-midi-io": "Поддержка MIDI-клавиатуры",
    "feature-midi-io-description":
        "Браузеры, поддерживающие Web MIDI API, позволяют подключать MIDI-клавиатуру для записи исполнения и воспроизведения звуков с помощью аппаратного синтезатора.",
    "feature-export-audio": "Быстрый экспорт",
    "feature-export-audio-description":
        "Вы можете экспортировать созданную песню в файл WAV и слушать ее на своем смартфоне, использовать в качестве фоновой музыки для видео или импортировать в DAW.",
    "time-signature": "Тактовый размер",
    "add-time-signature": "Добавить тактовый размер",
    "remove-time-signature": "Удалить такторвый размер",
    support: "Поддержка",
    "sponsor-intro":
        "signal — это приложение, которое я делаю в качестве хобби по выходным. Если вы понимаете концепцию легкого программного обеспечения для создания музыки, которое работает в вашем браузере, пожалуйста, поддержите нас.",
    "support-github-desctiption": "Помощь GitHub",
    "become-sponsor": "Стать спонсором?",
    "open-github-sponsors": "Открыть GitHub",
    "follow-twitter": "Подписаться на Twitter",
    file: "Файл",
    "new-song": "Новая песня",
    "open-song": "Открыть",
    "save-song": "Сохранить",
    "save-as": "Сохранить как",
    "song-created": "Песня создана",
    "song-saved": "Песня сохранена",
    "untitled-song": "Песня без названия",
    name: "Имя",
    rename: "Переименовать",
    track: "Дорожка",
    tracks: "Дорожки",
    "add-track": "Добавить трек",
    "delete-track": "Удалить трек",
    "duplicate-track": "Дублировать трек",
    channel: "Канал",
    categories: "Категории",
    instruments: "Инструменты",
    "rhythm-track": "Ритм-трек",
    "conductor-track": "Проводник трек",//chzh
    "track-name": "Название трека",
    cancel: "Отмена",
    ok: "Ок",
    triplet: "Триоли",
    dotted: "Точки",
    "confirm-new": "Редактируемый трек удаляется. Вы уверены, что хотите создать новый?",
    "confirm-open": "Редактируемый трек удаляется. Вы уверены, что хотите открыть другой?",
    "confirm-close": "Редактируемый трек удаляется. Вы уверены, что хотите закрыть страницу?",
    "auto-scroll": "Автоматическая прокрутка",
    help: "Помощь",
    close: "Закрыть",
    "keyboard-shortcut": "Сочетание клавиш",
    "play-pause": "Воспроизведение/пауза",
    rewind: "Перемотка назад",
    "fast-forward": "Перемотка вперед",
    "forward-rewind": "Быстрая перемотка вперед/назад",
    "next-previous-track": "Следующая дорожка/предыдущая дорожка",
    "solo-mute-ghost": "Переключение между соло, немыми и призрачными треками",
    stop: "Остановиться",
    record: "Запись",
    "pencil-tool": "Карандаш",
    "selection-tool": "Выделение",
    "copy-selection": "Копировать выделеное",
    "cut-selection": "Вырезать выделеное",
    "paste-selection": "Вставить выделеное",
    "select-all": "Выбрать всё",
    "delete-selection": "Убрать выделение",
    "move-selection": "Переместить выделение",
    undo: "Отменить",
    redo: "Переделать",
    cut: "Вырезать",
    copy: "Копировать",
    paste: "Вставить",
    duplicate: "Дублировать",
    delete: "Удалить",
    "select-note": "Выбрать заметку",
    "scroll-horizontally": "Горизонтальный скрол",
    "scroll-vertically": "Вертикальный скрол",
    settings: "Настройки",
    "midi-settings": "Настройки MIDI",
    inputs: "Входы",
    outputs: "Выходы",
    "no-inputs": "Устройство ввода не найдено",
    "one-octave-up": "+1 октава",
    "one-octave-down": "-1 октава",
    arrange: "Аранжировка",
    "arrangement-view": "Упорядочить вид",
    "open-help": "Открыть справку",
    "event-list": "Список событий",
    "open-chat": "Открыть чат",
    property: "Свойство",
    quantize: "Квантовать",
    "snap-to-grid": "Привязки к сетке",
    "export-audio": "Экспорт аудио",
    export: "Экспорт",
    "exporting-audio": "Экспортирование аудио...",
    "file-type": "Формат файла",
    "export-error-too-short": "Песня слишком коротная",
    "set-loop-start": "Установить начальную позицию цикла",
    "set-loop-end": "Установить конечную позицию цикла",
    "switch-tab": "Переключить вкладку",
    transpose: "Переместить",
    yes: "Да",
    no: "Нет",
    "please-sign-up": "Подпишитесь на облачные сохранения",
    "save-changes": "Сохранить изменения?",
    "sign-in": "Войти",
    "sign-out": "Выйти",
    "success-sign-in": "Вы успешно вошли",
    files: "Файлы",
    "created-date": "Дата создания",
    "modified-date": "Дата изменеия",
    "cloud-beta-warning":
        "Облачная функция — это бета-версия, которая находится в стадии разработки, поэтому, пожалуйста, загружайте важные песни почаще.",
    "cloud-description":
        "Войдя в систему, вы можете сохранить свою музыку в облаке и возобновить сочинение в любое время и в любом месте.",
    "import-midi": "Импорт MIDI",
    "export-midi": "Экспорт MIDI",
    general: "Общий",
    /* MIDI Instrument Categories */
    Piano: "Пианино",
    "Chromatic Percussion": "Хроматическая перкуссия",
    Organ: "Орган",
    Guitar: "Гитара",
    Bass: "Бас",
    Strings: "Струны",
    Ensemble: "Ансамбль",
    Brass: "Духовые",
    Reed: "Тростевые",
    Pipe: "Дудка",
    "Synth Lead": "Синтезатор-соло",
    "Synth Pad": "Синтезатор",
    "Synth Effects": "Синтезаторный эффект",
    Ethnic: "Народный инструмент",
    Percussive: "Ударные",
    "Sound effects": "Звуковые эффекты",
    /* MIDI Instruments */
    "Acoustic Grand Piano": "Большой акустический рояль",
    "Bright Acoustic Piano": "Яркий акустический рояль",
    "Electric Grand Piano": "Электрический рояль",
    "Honky-tonk Piano": "Хонки-тонк фортепиано",
    "Electric Piano 1": "Электрическое пианино 1",
    "Electric Piano 2": "Электрическое пианино 2",
    Harpsichord: "Клавесин",
    Clavinet: "Клавинет",
    Celesta: "Челеста",
    Glockenspiel: "Колокольчики",
    "Music Box": "Музыкальный ящик",
    Vibraphone: "Вибрафон",
    Marimba: "Маримба",
    Xylophone: "Ксилофон",
    "Tubular Bells": "Колокола",
    Dulcimer: "Дульцимер",
    "Drawbar Organ": "Механический орган",
    "Percussive Organ": "Ударный орган",
    "Rock Organ": "Рок-орган",
    "Church Organ": "Церковный орган",
    "Reed Organ": "Фисгармония",
    Accordion: "Аккордеон",
    Harmonica: "Гармоника",
    "Tango Accordion": "Танго аккордеон",
    "Acoustic Guitar (nylon)": "Акустическая гитара (нейлон)",
    "Acoustic Guitar (steel)": "Акустическая гитара (металл)",
    "Electric Guitar (jazz)": "Электрогитара (джаз)",
    "Electric Guitar (clean)": "Электрогитара (чистый)",
    "Electric Guitar (muted)": "Электрогитара (приглушенный)",
    "Overdriven Guitar": "Перегруз",
    "Distortion Guitar": "Дисторшн",
    "Guitar Harmonics": "Гитарные гармоники",
    "Acoustic Bass": "Акустический бас",
    "Electric Bass (finger)": "Электрический бас (палец)",
    "Electric Bass (pick)": "Электрический бас (щипковый)",
    "Fretless Bass": "Безладовый бас",
    "Slap Bass 1": "Слэп-бас 1",
    "Slap Bass 2": "Слэп-бас 2",
    "Synth Bass 1": "Синт-бас 1",
    "Synth Bass 2": "Синт-бас 2",
    Violin: "Скрипка",
    Viola: "Альт",
    Cello: "Виолончель",
    Contrabass: "Констрабас",
    "Tremolo Strings": "Тремоло струнных",
    "Pizzicato Strings": "Пиццикато струнных",
    "Orchestral Harp": "Оркестровая арфа",
    Timpani: "Литавры",
    "String Ensemble 1": "Струнный ансабль",
    "String Ensemble 2": "Струнный ансабль (медленный)",
    "Synth Strings 1": "Синт-струны 1",
    "Synth Strings 2": "Синт-струны 2",
    "Choir Aahs": "Хор - а",
    "Voice Oohs": "Хор - о",
    "Synth Choir": "Синт-голос",
    "Orchestra Hit": "Оркестровый тутти",
    Trumpet: "Труба",
    Trombone: "Тромбон",
    Tuba: "Туба",
    "Muted Trumpet": "Приглушенная труба",
    "French Horn": "Валторны",
    "Brass Section": "Духовая секция",
    "Synth Brass 1": "Синт-духовые 1",
    "Synth Brass 2": "Синт-духовые 2",
    "Soprano Sax": "Саксофон-сопрано",
    "Alto Sax": "Саксофон-альт",
    "Tenor Sax": "Саксофон-тенор",
    "Baritone Sax": "Саксофон-баритон",
    Oboe: "Гобои",
    "English Horn": "Английский рожок",
    Bassoon: "Фагот",
    Clarinet: "Кларнет",
    Piccolo: "Флейта-пикколо",
    Flute: "Флейта",
    Recorder: "Рекордер",
    "Pan Flute": "Флейта-пана",
    "Blown Bottle": "Дутье в бутылку",
    Shakuhachi: "Шикухачи",
    Whistle: "Свист",
    Ocarina: "Окарина",
    "Lead 1 (square)": "Соло-прямоугольник",
    "Lead 2 (sawtooth)": "Соло-пила",
    "Lead 3 (calliope)": "Соло-калиопе",
    "Lead 4 (chiff)": "Соло-чиф",
    "Lead 5 (charang)": "Соло-чаранг",
    "Lead 6 (voice)": "Соло-голос",
    "Lead 7 (fifths)": "Соло-квинты",
    "Lead 8 (bass + lead)": "Бас + соло",
    "Pad 1 (new age)": "Pad 1 новый век",
    "Pad 2 (warm)": "Pad 2 новый теплая",
    "Pad 3 (polysynth)": "Pad 3 полисинтетическая",
    "Pad 4 (choir)": "Pad 4 хор",
    "Pad 5 (bowed)": "Pad 5  смычковые",
    "Pad 6 (metallic)": "Pad 6 металл",
    "Pad 7 (halo)": "Pad 7 гало",
    "Pad 8 (sweep)": "Pad 8 свип",
    "FX 1 (rain)": "Дождь",
    "FX 2 (soundtrack)": "Саундтрек",
    "FX 3 (crystal)": "Кристалл",
    "FX 4 (atmosphere)": "Атмосфера",
    "FX 5 (brightness)": "Яркость",
    "FX 6 (goblins)": "Гоблин",
    "FX 7 (echoes)": "Эхо",
    "FX 8 (sci-fi)": "Sci-fi",
    Sitar: "Ситар",
    Banjo: "Банджо",
    Shamisen: "Шамисен",
    Koto: "Кото",
    Kalimba: "Калимба",
    Bagpipe: "Волынка",
    Fiddle: "Фидл-скрипка",
    Shanai: "Шанай",
    "Tinkle Bell": "Звон колокольчика",
    Agogo: "Агого",
    "Steel Drums": "Стальные барабаны",
    Woodblock: "Деревянный блок",
    "Taiko Drum": "Барабан-тайко",
    "Melodic Tom": "Мелодический барабан",
    "Synth Drum": "Синт-барабан",
    "Reverse Cymbal": "Реверсивная тарелка",
    "Guitar Fret Noise": "Звук ладов гитары",
    "Breath Noise": "Дыхание ветра",
    Seashore: "Морской прибой",
    "Bird Tweet": "Птичий свист",
    "Telephone Ring": "Телефонный звонок",
    Helicopter: "Вертолет",
    Applause: "Аплодисменты",
    Gunshot: "Выстрел",
  },
  en: {
    "app-intro": "Fully Open-sourced Online MIDI Editor",
    "app-desc": "Start making music without installing anything"
  }
} as { [key: string]: { [key: string]: string } }
